server:
  port: 8071
spring:
  application:
    name: configserver
  profiles:
    #    active: native
    active: git
  cloud:
    config:
      server:
      #        native:
      #          search-locations: "classpath:/config"
      #          search-locations: "file:///c://Users//Documents//config"
      git:
        uri: "https://github.com/manikanta240599/microservices/config.git"
        default-label: main
        timeout: 5
        clone-on-start: true
        force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"